project:
  type: website

website:
  title: "Welcome to ORL website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



